### ISSUE TITLE
Unhandled exception after moving renamed tab

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/Just-Data#103]
If you have renamed tab (not saved, new tab and rename it) and try to move it after other tab, you get unhandled exception
![obraz](https://user-images.githubusercontent.com/93384978/142821893-cf18eedd-78a0-4b96-a289-8f6d349a3367.png)

**Comment by KrzysztofDusko** [comment]
related with 
https://github.com/KrzysztofDusko/Just-Data/issues/63

**Comment by andrzejchmiel3** [comment]
Seems fine now, thank you.
