### ISSUE TITLE
Znacznik kolumny NOT NULL

### ISSUE THREAD

**Issue by elaslowska** [KrzysztofDusko/Just-Data#109]
Brak widocznego znacznika kolumny typu NOT NULL przy typie danych

**Comment by KrzysztofDusko** [comment]
**netezza.**  (dla np. DB2 to już jest)

**Comment by KrzysztofDusko** [comment]
sprawdź proszę dla wersji >= 20211129

**Comment by elaslowska** [comment]
Dzięki, jest ok.
