### ISSUE TITLE
Query finished in background - small issue and enchancement idea

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/Just-Data#111]
I'm running any query (select 1) in tab, then I'm swithing  to other tab until the query is finished (I mean other tab in just-data, other SQL window on the top).
- [ ]  we are not notified at all that the query has finished. You made such enchacement when justdata is running in background (flickering justdata icon), but when justdata is active, but on another tab - we get nothing. It would be nice to also be notified in any way, for example flickering tab on the top (one with results ready)

- [ ]  when switchng back to first tab with results ready, on the bottom i have active 'LOG' tab instead of 'result'. By default, 'result' should be the active one, as is in most cases.

**Comment by KrzysztofDusko** [comment]
1. I can offer sound and collor 
![image](https://user-images.githubusercontent.com/69449360/145264631-dfa87d98-edba-4b6c-a0d9-3839091819bc.png)
2.Fixed

**Comment by andrzejchmiel3** [comment]
Ok, seems good. 
Thank you, closing.
