### ISSUE TITLE
Abort button visible and active after query/batch is completed

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/Just-Data#112]
After running successful query (select 1) or any batch of multiple queries, we still can see Abort button, and it is still clickable (click seems to do nothing except turning inactive).
I think it should at least turn non-active on successful completion (as we get in unsuccessful queries like select 1/0), and maybe even show something other there (like "ready") to communicate there is nothing to abort anymore

**Comment by KrzysztofDusko** [comment]
please check (>= 20211206)

**Comment by andrzejchmiel3** [comment]
Great, now it behaves like one would expect it to. Thanks.
