### ISSUE TITLE
too many rows warning does not work

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/Just-Data#131]
While reaching warning level of rows, we are asked if to conitnue. Despite clicking no, I'm still getting more rows. So it seems like that 'do not continue' part of warning does not work.
Example, set warining limit to 10 and try code below. Clicking 'No' on warning window still yields 15 rows
select 1
union all select 1
union all select 1
union all select 1
union all select 1
union all select 1
union all select 1
union all select 1
union all select 1
union all select 1
union all select 1
union all select 1
union all select 1
union all select 1
union all select 1

**Comment by KrzysztofDusko** [comment]
please check >= 20211209

**Comment by andrzejchmiel3** [comment]
Now it seems ok, thank you
