### ISSUE TITLE
Custom color yield different results than chosen

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/Just-Data#151]
With version update, colors of menu havechanged to some werid red-ish (Im using custom colors). Nothing in config seems to correspond to those:
"BackgroundFastColored": [
    250,
    253,
    253,
    255
  ],
  "SelectionColorFastColored": [
    0,
    102,
    204,
    255
  ],
  "DisabledColorFastColored": [
    192,
    192,
    192,
    255
  ],
  "IndentBackColorFastColored": [
    192,
    192,
    192,
    255
  ],
  "LineNumberColorFastColored": [
    64,
    64,
    64,
    255
  ],
  "FoldingIndicatorColorFastColored": [
    0,
    0,
    0,
    255
  ],
  "ForeColorFastColored": [
    10,
    10,
    20,
    255
  ],
  "FontkeyWordsStyle1": [
    0,
    20,
    250,
    255
  ],
  "FontkeyWordsStyle2": [
    230,
    0,
    230,
    255
  ],
  "FontparamStyle": [
    0,
    192,
    192,
    255
  ],
  "FontmyCommandsStyle": [
    128,
    128,
    128,
    255
  ],
  "FontnumberStyle": [
    128,
    0,
    0,
    255
  ],
  "FontcommentsStyle": [
    0,
    128,
    0,
    255
  ],
  "FontstringsStyle": [
    252,
    40,
    40,
    255
  ],
  "FontsameWordsStyle": [
    189,
    183,
    107,
    100
  ],
  "DgvDefaultCellStyleBackColor": [
    250,
    253,
    253,
    255
  ],
  "DgvAlternatingRowsDefaultCellStyleBackColor": [
    211,
    211,
    211,
    255
  ],
  "DgvDefaultCellStyleForeColor": [
    0,
    0,
    0,
    255
  ],
  "DgvRowHeadersDefaultCellStyleBack": [
    217,
    217,
    217,
    255
  ],
  "DgvColumnHeadersDefaultCellStyleFore": [
    0,
    0,
    0,
    255
  ],
  "DgvColumnHeadersDefaultCellStyleBack": [
    227,
    227,
    227,
    255
  ],
  "DocMapBackColor": [
    245,
    255,
    245,
    255
  ],
  "DocMapForeColor": [
    62,
    251,
    62,
    255
  ],
  "TabColor": [
    200,
    200,
    210,
    255
  ],
  "SelectedtabColor": [
    134,
    134,
    124,
    255
  ],
  "TabTitleColor": [
    0,
    0,
    0,
    255
  ],
  "StripBack": [
    230,
    230,
    230,
    255
  ],
  "StripFore": [
    0,
    0,
    0,
    255
  ],
  "TreeViewBackColor": [
    248,
    248,
    251,
    255
  ],
  "TreeViewForeColor": [
    0,
    0,
    0,
    255
  ],
  "TreeViewLineColor": [
    169,
    169,
    169,
    255
  ],
  "TextBoxFileSearchBackColor": [
    250,
    253,
    253,
    255
  ],
  "TextBoxFileSearchForeColor": [
    128,
    128,
    128,
    255
  ],
  "MenuItemSelected": [
    64,
    64,
    64,
    255
  ],
  "MenuItemSelectedGradientBegin": [
    192,
    192,
    192,
    255
  ],
  "MenuItemSelectedGradientEnd": [
    128,
    128,
    128,
    255
  ],
  "MenuItemBorder": [
    105,
    105,
    105,
    255
  ],
  "MenuItemPressedGradientBegin": [
    192,
    192,
    192,
    255
  ],
  "MenuItemPressedGradientMiddle": [
    64,
    64,
    64,
    255
  ],
  "MenuItemPressedGradientEnd": [
    128,
    128,
    128,
    255
  ],
  "ButtonSelectedHighlightBorder": [
    128,
    128,
    128,
    255
  ],
  "GroupingRowColorBack": [
    170,
    170,
    200,
    255
  ],

**Comment by KrzysztofDusko** [comment]
check please with 20220119
