### ISSUE TITLE
Some issues when internet connection lost

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/Just-Data#158]
When internet connection is lost (disabled VPN, or simply pulling the plug) there are few issues:

1. If schema is not fully loaded (which I understand as, when you try to expand schema on database you weren't previously on, it normally takes some time to load / refresh, graying schema tree for w while) and then you lose connection, trying to expand a schema result in unhandled exception:
![obraz](https://user-images.githubusercontent.com/93384978/151194967-19eefc8a-7cd5-4486-bec0-0dbfb25941c4.png)

```

> Szczegółowe informacje na temat wywoływania debugowania w trybie JIT (just in time)
> zamiast tego okna dialogowego znajdują się na końcu tego komunikatu.

> ************** Tekst wyjątku **************
> System.Exception: ERROR [HYT00] Timeout expired
>    at JustData.Netezza.makeOneDb(String connectionName, String baza) in C:\Users\dusko\source\repos\NZ-SQL-IDE\JustData\Netezza.cs:line 475
>    at JustData.Netezza.<>c__DisplayClass21_0.<DownloadOneDb>b__0() in C:\Users\dusko\source\repos\NZ-SQL-IDE\JustData\Netezza.cs:line 1082
>    at System.Threading.Tasks.Task.InnerInvoke()
>    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
> --- End of stack trace from previous location ---
>    at JustData.Netezza.DownloadOneDb(Form form, String connectionName, String databaseName, Boolean deleteTempDbs) in C:\Users\dusko\source\repos\NZ-SQL-IDE\JustData\Netezza.cs:line 1080
>    at JustData.BaseWindow.addOneDbToNetezzaSchemaTree(String connectionName, Netezza netezza, String dbName) in C:\Users\dusko\source\repos\NZ-SQL-IDE\JustData\OknoBazowe.cs:line 18089
>    at JustData.BaseWindow.treeViewBaza_BeforeExpand(Object sender, TreeViewCancelEventArgs e) in C:\Users\dusko\source\repos\NZ-SQL-IDE\JustData\OknoBazowe.cs:line 17814
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
```
2. If you try  to refresh whole database (with no connection, so failed result of course) and quit Justdata and run it again, you end up with  blank database tree with no possible way to refresh it, even if internet connection is restored. "Refresh table list" does not work, logging again does not work. Only way is to restart justdata and let it download whole database.

3. With blank database tree like in 2. , last two buttons:
![obraz](https://user-images.githubusercontent.com/93384978/151195716-b6cdfbb7-c862-4126-9d65-5764c8ead519.png)

result in not really helpful pop-up:
![obraz](https://user-images.githubusercontent.com/93384978/151195812-cd780c1b-dcb1-4664-bc54-175f24ee8522.png)
Of course using them is pointless when no database is loaded, but still that is funny pop-up content for a user

**Comment by andrzejchmiel3** [comment]
and by the way, there is a typo when trying to run some select with no connection:
![obraz](https://user-images.githubusercontent.com/93384978/151197716-dd1a67e0-4165-4787-9b2d-3ab88afe17de.png)
This message also seems more like debugging log than info for user, especially that it does not refer (in that pop-up message) to select i ran some seconds ago

**Comment by KrzysztofDusko** [comment]
DB2


Szczegółowe informacje na temat wywoływania debugowania w trybie JIT (just in time)
zamiast tego okna dialogowego znajdują się na końcu tego komunikatu.

************** Tekst wyjątku **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at JustData.BaseWindow.refreshSchemaFullOrNot(String conName, NetezzaRefreshMode refreshMode) in C:\Users\dusko\source\repos\NZ-SQL-IDE\JustData\OknoBazowe.cs:line 15351
   at JustData.BaseWindow.refreshTableList(Object sender, EventArgs e) in C:\Users\dusko\source\repos\NZ-SQL-IDE\JustData\OknoBazowe.cs:line 15324
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

**Comment by KrzysztofDusko** [comment]
please check with >= 20220127

**Comment by andrzejchmiel3** [comment]
Now it seems a lot better, none of above happen on last version, thank you
