### ISSUE TITLE
navigating with keyboard in result window have a slight problem

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/Just-Data#166]
If you have enough columns so query results do not fit on screen (and then we get a scrollbar), navigating with arrow keys (generally with keyboard) have a problem:
When pressing 'arrow right' key until I reach 'end', that 'end' seem to be considered by width of first row of last column. This way  I can't see whole last column, just the part cut to width of first row. That means -  by using arrows only I can't scroll to the end (and so I have to use mouse on scrollbar to scroll to real end)

Should be easier to understand with example:
Use code below, while having database tree on the left very wide, so wide that results below won't fit entirely on screen:
```
select 'a' as kol1
, 'v' as kol2
, 'c' as kol3
union all

select 'aaaaaaaaaaaaaaaaaaaaaaaaaaa' as kol1
, 'aaaaaaaaaaaaaaaaaaaaaaaaaaa' as kol2
, 'too long text that, so long that I cant read all of it ' as kol3
```
![obraz](https://user-images.githubusercontent.com/93384978/152543446-16318def-b4a6-4d26-a9c9-fd6e72e54c97.png)

press 'arrow right' to get to last column of results. It won't get you to the end, just to the part visible on screenshot. And there seems to be now way to get (with keyboard only) to the same 'right side' as I can get to with mouse:
![obraz](https://user-images.githubusercontent.com/93384978/152543716-b24d63b4-4b98-4e97-8888-d85ef2f1451d.png)

**Comment by KrzysztofDusko** [comment]
please check with version >= 20220307

**Comment by andrzejchmiel3** [comment]
Seems fine, thank you
