### ISSUE TITLE
Erorr highlight reset

### ISSUE THREAD

**Issue by B4rt0** [KrzysztofDusko/Just-Data#204]
Action of running query using hotkey or UI button should remove all prior error highlighting in the code.

Background: Not all errors are a result of error in the code itself, for example it may be caused by mistakenly selecting part of the code that isn't a complete statement or by using wrong database schema to run the code.

**Comment by KrzysztofDusko** [comment]
i totaly agree.. please check with _2023.01.19.01_ version

**Comment by B4rt0** [comment]
Yes, that's what I meant. It works fine now. Thanks.
