### ISSUE TITLE
problem po aktualizacji

### ISSUE THREAD

**Issue by marekjasvelo** [KrzysztofDusko/Just-Data#211]
Po ostatniej aktualizacji aplikacja nie nawiązuje połączenia z bazą danych. Nie mam komunikatu błędu i nie mogę nigdzie się wklikać.
![justdata](https://user-images.githubusercontent.com/127832982/226383447-76df90f5-89ec-4d2b-bf23-8354e101aad6.png)

**Comment by KrzysztofDusko** [comment]
najlepiej ponownie zainstaluj JD = instrukcję przekazałem mailem.
