### ISSUE TITLE
Pytania o zakres przetwarzanych danych

### ISSUE THREAD

**Issue by KrzysztofVl** [KrzysztofDusko/Just-Data#214]
Służbowo otrzymałem takie pytania
- _jakie dane są przesyłane_
- _gdzie_
- _jaka technologia jest używana do tego połączenia_

**Comment by KrzysztofDusko** [comment]
przykład:
https://visualstudio.microsoft.com/pl/license-terms/vs2022-ga-proenterprise/
_Zbieranie danych. Oprogramowanie może gromadzić informacje o Licencjobiorcy i sposobie, w jaki używa on oprogramowania, a także przesyłać takie informacje do Microsoft. Microsoft może wykorzystywać te informacje w celu świadczenia usług oraz w celu ulepszenia produktów i usług Microsoft. Licencjobiorca może zrezygnować z wielu scenariuszy (ale nie wszystkich), jak opisano w dokumentacji oprogramowania. Istnieją również pewne funkcje oprogramowania, które mogą umożliwiać Licencjobiorcy i Microsoft zbieranie danych od użytkowników aplikacji Licencjobiorcy. Jeśli Licencjobiorca używa tych funkcji, musi przestrzegać przepisów prawa właściwego, w tym stosownie powiadamiać użytkowników aplikacji Licencjobiorcy o tych działaniach, a także udostępnić im kopię przyjętego przez Microsoft oświadczenia o ochronie prywatności. Nasze oświadczenie o ochronie prywatności znajduje się pod adresem https://aka.ms./privacy. Więcej informacji na temat zbierania i używania danych można znaleźć w dokumentacji oprogramowania i oświadczeniu Microsoft o ochronie prywatności. Korzystanie przez Licencjobiorcę z oprogramowania oznacza zgodę na takie działania._

**Comment by KrzysztofVl** [comment]
przykłady.. 
https://www.gov.pl/web/uw-opolski/klauzula-informacyjna-dla-osob-fizycznych-prowadzacych-dzialalnosc-gospodarcza

- realizacja umowy -  w zakresie niezbędnym do wykonania umowy (art. 6 ust. 1 lit. b RODO)

- realizacja obowiązków wynikających z ustawy o rachunkowości (art. 6 ust. 1 lit. c RODO),

- realizacja obowiązków podatkowych wynikających z przepisów podatkowych (art. 6 ust. 1 lit. c RODO),

- dochodzenie roszczeń lub obroną przed ewentualnymi roszczeniami - w celu realizacji prawnie uzasadnionego interesu administratora polegającego na dochodzeniu swoich praw majątkowych lub niemajątkowych lub ochrony przed roszczeniami wobec administratora, zgodnie z przepisami ogólnymi, w szczególności z Kodeksem cywilnym (art. 6 ust. 1 lit. f RODO)
- 
- dane osobowe będą przechowywane przez okres wynikający z obowiązku archiwizacyjnego oraz w oparciu o uzasadniony interes realizowany przez Administratora, którym jest  obrona naszych interesów.
