### ISSUE TITLE
netezza - problem z licencją

### ISSUE THREAD

**Issue by TomaszSmietanski** [KrzysztofDusko/Just-Data#216]
Cześć, po połączeniu z bazą nie odświeża się schemat oraz przy próbie odpytania bazy za każdym razem pojawia się ekran z licencją bez możliwości odpytania bazy.

**Comment by KrzysztofDusko** [comment]
dziękuję za wysiłek włożony w zrobienie tego zgłosznia

**Comment by KrzysztofDusko** [comment]
problem w mojej opinii już nie występuję.
