### ISSUE TITLE
Więcej formatów liczb / format uzależniony od precyzji

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/Just-Data#51]
Obecnie w opcjach mamy możliwość wyboru formatów na dwie liczby: typu integer (także smallint, bigint) oraz decimal (numeric ). Ale numerici mogą być różne i przydałoby się móc inaczej sformatować numeric(32,0), który jest prawie że integerem, inaczej numeric(32,2), a jeszcze inaczej numeric (14,9)

Także jedna sprawa to numeric(32,0), czy ogólnie z zerem na końcu - niektórzy tak zapisują liczby będące integerami, więc dobrze by było móc to sformatować jako integer niezależnie od pozostałych numericów.

Druga sprawa to precyzja większa od zera - dobrze by było móc pokazywać format liczby uzależniony od precyzji, tzn. jak mamy pole numeric(30,2) to żeby pokazywał w formacie N2, a numeric(30,6) w formacie N6

Alternatywnym rozwiązaniem byłaby możliwość ręcznego dopisywania formatów na konkretne typy danych, choćby do configu

```
select 
123::byteint
,12345::smallint  
,12345::int
,12345::bigint
,12345::numeric(20,0)
,12345::numeric(20,4)
,12345::numeric(14,9)
```

**Comment by andrzejchmiel3** [comment]
Ogólnie działa to zgodnie z oczekiwaniami i na Netezzie i na DB2. Jedyne co teraz zostało nieco dziwne, to INT się wyrównuje do lewej a numeric(20,0) do prawej. Ale nie jest to problemem, może nawet to pozwolić odróżnić int od numerica, więc dla mnie ok
```
select 
12345::int
,12345::numeric(20,0)
```

**Comment by KrzysztofDusko** [comment]
Domyślnie w  DBeaver są oba do prawej, a Aginity Workbench były oba do lewej. W Aginity pro oba do prawej
-> dam oba do prawej na zasadzie, "przegłosowano"
