### ISSUE TITLE
Zaznaczanie problemów przy błędnych kodach nie odznacza się przy zmianie bazy

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/Just-Data#52]
Mam na myśli zaznaczanie na czerwono fragmentu kodu jaki może być problematyczny jeśli baza zwróci błąd w kodzie. Normalnie to się odznacza (przywraca normalne formatowanie kodu) przy jakiejkolwiek edycji kodu. Ale nie odznacza się przy zmianie bazy.
Także mając kod puszczony na 'złej' bazie, zaznacza się na czerwono
![obraz](https://user-images.githubusercontent.com/93384978/139439873-59b98808-1eeb-48e6-9853-551a3c28cd42.png)
Po czym zmieniam baze na 'dobrą', kod się wykręca, wszystko ok, a nadal jest zaznaczone na czerwono
![obraz](https://user-images.githubusercontent.com/93384978/139439963-448fe277-5d2d-4a2e-81ec-cce5d9b00b69.png)

**Comment by KrzysztofDusko** [comment]
proszę o sprawdzenie

**Comment by andrzejchmiel3** [comment]
Teraz jest ok, dziękuję

**Comment by KrzysztofDusko** [comment]
nie koloruje się prawidłowo 
np przełaczenia bazy jak mamy takie cos :
--CREATE
