### ISSUE TITLE
About & licence - tekst jest niekopiowalny, linki nieklikalne

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/Just-Data#58]
W About & licence są adresy, których nie można skopiować ani kliknąć, jedyna możliwość to ręczne przepisanie.
Open in browser co prawda otwiera te linki, ale nie sugeruje co otworzy, także nie wiem przed kliknięciem że to otworzy wszystkie powyższe linki

**Comment by KrzysztofDusko** [comment]
ponad to licence -> license.

**Comment by KrzysztofDusko** [comment]
zobacz teraz

**Comment by andrzejchmiel3** [comment]
Teraz jest ładnie i przejrzyście. Dziękuje, zamykam

**Comment by KrzysztofDusko** [comment]
ale zabrakło linku do polityki prywatności
https://github.com/KrzysztofDusko/Just-Data/blob/main/PrivacyPolicy
