### ISSUE TITLE
Rozwijanie * do listy kolumn / select każdą kolumnę

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/Just-Data#67]
Przydałaby się możliwość w jakikolwiek sposób wygenerować listę kolumn do selecta.  Tzn. mam tabelę
```
create table tab_test_asdfasfgas as
select 1 as kol1 , 2 as kol2 , '3' as kol3;
```

i teraz chciałbym móc jakoś wygenerować selecta, ale żeby nie mieć gwiazdki, tylko listę kolumn
```
SELECT
    kol1
    ,kol2
    ,kol3
FROM  tab_test_asdfasfgas
```

Teraz mogę (i to na kilka sposobów) dostać jedynie listę jak poniższa, ale to nie załatwia sprawy, bo przejście z poniższego do powyższego przy dużej liczbie kolumn oznacza ręczne kasowanie tych typów danych.

```
CREATE TABLE GNB_MIS."a.chmiel3".TAB_TEST_ASDFASFGAS (
    KOL1 INTEGER
    , KOL2 INTEGER
    , KOL3 CHARACTER VARYING(1)
)
DISTRIBUTE ON RANDOM;
```

Najlepiej byłoby móc 'rozszerzyć' gwiazdkę do listy kolumn, szczególnie jak mamy kilka joinów (tutaj przycisk "try add aliases" można o to przeciążyć).
Ale równie dobrze można to zrobić klikając prawym na tabelę na schemacie albo ctrl+klik. Mamy już tam select..., ale to daje z gwiazdką. Mógłby być też select columns...

**Comment by KrzysztofDusko** [comment]
SELECT    @@C <TU SIĘ POJAWI SNIPET>    FROM BAZA..TABELA C

**Comment by KrzysztofDusko** [comment]
czy to nie spełnia wymagań ?

**Comment by andrzejchmiel3** [comment]
Hmm, nie znałem tego. Ok, jak najbardziej, działa, spełnia wymagania. Dziękuję, zamykam
