### ISSUE TITLE
wskazywanie błędnego miejsca w kodzie

### ISSUE THREAD

**Issue by akolak357** [KrzysztofDusko/Just-Data#69]
Hej, ta opcja z zaznaczaniem w treści kodu na czerwono błędnych wpisów jest super, ale:
załóżmy, że mam bardzo długi kod, składający się z kilku select'ów, kolumna 'ID_KLIENTA' pojawia się w każdym z nich, ale dopiero w ostatnim jest użyta błędnie. Zaznaczam i uruchamiam wyłącznie ostatni select. Uruchomienie kończy się błędem "Attribute 'ID_KLIENTA' not found" Kursor przeskakuje do pierwszego 'ID_KLIENTA' w całym kodzie - czy dałoby się ograniczyć obszar wskazywania błędu do uruchomionego fragmentu kodu?

**Comment by KrzysztofDusko** [comment]
Zakładam że chodzi o Netezzę. 
Temat nie jest prosty dlatego nie zostało to zrobione od razu. Temat był szerzej dyskutowany ale poza githubem (w szerszym kontekście słabości funkcji zaznaczania błędów). Tutaj zostawię bo takie standardowe użycie (zwykłe F5) można faktycznie polepszyć (choć nadal jak jest kilka tabel tymczasowych błąd może się tyczyć tylko jeden z nich). Prawdziwe rozwiązanie polegałoby bardziej aby sterownik ODBC/OleDb/Net został poprawiony przez IBM do formy która wskazuje gdzie dokładnie znajduje się problematyczna kolumna.

**Comment by KrzysztofDusko** [comment]
ERROR [HY000] ERROR: Attribute ALIAS.KOLUMNA must be GROUPed or used in an aggregate function
ERROR [42S02] ERROR: Function 'DATE_TRUNC(DATE)'
^ found "THN" (at char 555) expecting AND' or AT' or BETWEEN' or IN' or `IS'
ERROR [HY000] ERROR: Cannot find column "COLUMN_NAME"
ERROR [HY000] ERROR: Attribute 'COLUMN_NAME' is repeated. Must have an appropriate alias
ERROR [HY000] ERROR:  Column 2 : Field cannot contain null values
ERROR [HY000] ERROR:  'VATALOG' is not a valid option name

**Comment by KrzysztofDusko** [comment]
Tu informacyjnie, użycie innych sterowników może rozwiązać problem.

**Comment by KrzysztofDusko** [comment]
```
SELECT ID_KLIENTA; -- źle ale nieoznaczone

SELECT ID_KLIENTA ; -- źle

SELECT ID_KLIENTA FROM (SELECT 1 as ID_KLIENTA) AS PODZAPYTANIE; -- dobrze
SELECT ID_KLIENTA ; -- źle
```

1. 
![image](https://user-images.githubusercontent.com/69449360/152036532-190815fc-88d4-449d-b708-ca30237623c7.png)
f5 -> 
![image](https://user-images.githubusercontent.com/69449360/152036572-267b73a9-da60-431d-a26d-9f1b7b2e20ab.png)

2.
![image](https://user-images.githubusercontent.com/69449360/152036620-dcf52fa3-a9e7-49ea-9a86-a87d5e1e3c3b.png)
f5 -> 
![image](https://user-images.githubusercontent.com/69449360/152036662-c1122094-da1b-4c9e-bed4-492d0ce50030.png)

zaznaczenie ostatniej linijki i dorzucenie enterów powoduje zaznaczenie tylko jednego wyrazu no i nie ma przeskoku kursora


![image](https://user-images.githubusercontent.com/69449360/152037359-da19e9db-fdec-417b-a92d-3d10b874bc6b.png)

**Comment by KrzysztofDusko** [comment]
wersja >= 20220202

**Comment by KrzysztofDusko** [comment]
jest OK
