### ISSUE TITLE
Paste context menu option to work normally for data in clipboard + settings improvement

### ISSUE THREAD

**Issue by B4rt0** [KrzysztofDusko/Just-Data#88]
Please consider making "paste" context menu option to always work like "normal" paste for data in clipboard since there is a dedicated option for importing data from clipboard as highlighted below:

![image](https://user-images.githubusercontent.com/9058055/141858301-6c15158f-4d39-46a7-9f73-d718242bf31c.png)

I'd also like to propose more understandable paste settings:

![paste settings](https://user-images.githubusercontent.com/9058055/141860298-64dce528-d00c-46bc-ad3b-e1ad28eca179.png)

Please also consider adding an option to change max 10000 cells limit when pasting using "1 2 -> (1,2)" and "A B -> ('A', 'B')" options.

**Comment by KrzysztofDusko** [comment]
To be clear
when auto import is selected (paste behavior). What should happen when in those scenarios?

- ctrl + v
- paste
- import from clipboard.

Import from clipobard always importing, pasting is depended of "paste behavior". Ctrl + v = paste right mouse button ?

**Comment by B4rt0** [comment]
From my perspective only ctrl + v should have this intelligent behavior based on the contents of clipboard like it is now, but user should be able to turn it off entirely. When it comes to context menu options - they should always present the same outcome.
So all in all:
- ctrl + v - affected by the setting
- paste - not affected by the setting, pastes into worksheet whatever is in clipboard (could be renamed to "paste into worksheet" to clearly indicate how it would work)
- import from clipboard - not affected by the setting, does as it says

That's what I personally think would be the best, but that is me and other users may think differently.

**Comment by KrzysztofDusko** [comment]
I fully agree. Thanks for pointing this out. This change will be avaiable in next update. Currnt users will be warned with popup

**Comment by B4rt0** [comment]
PS. I thought about settings sections names from my mockup and I would name "Paste behavior" -> "CTRL + V behavior" and "Paste method" -> "Import settings" or similar as those options also affect importing from file.

**Comment by KrzysztofDusko** [comment]
Please note that pasting xlsx (files not content) will also trigger importing and this behavior wont be changed (at this point)

**Comment by KrzysztofDusko** [comment]
some "advanced" options have been hidden by the way 
![image](https://user-images.githubusercontent.com/69449360/142019567-1d062b2a-24be-4b59-be2d-ef7a1f5b388f.png)
Changes will be live since 20211117 version.

**Comment by KrzysztofDusko** [comment]
implemented
