### ISSUE TITLE
autocomplete list opens up after "as"

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/Just-Data#98]
When aliasing column, (select 1 as ... ) we are getting autocomplete list to choose from. But in that case, it would be very rare to alias column with something from the list, like with another column or table name.
If possible, please adjust autocompletion so it won't show after "as"

See screenshot for example
![obraz](https://user-images.githubusercontent.com/93384978/142643688-7d37d337-b599-4374-affa-a5ed3f021ea5.png)

**Comment by KrzysztofDusko** [comment]
> 20211121

**Comment by andrzejchmiel3** [comment]
It solved problem I had, but I'm afraid it broke something else. From what i undestand, autocompletion is now disabled in whole row after "as". In joins however, it also disables autocompletion far after "as". Example below, after typing "tabbb." there is no autocompletion list.

```
select 1
from tab1
join tab2 as tabbb on tabbb.
```

**Comment by KrzysztofDusko** [comment]
please check this again

**Comment by andrzejchmiel3** [comment]
Now everything seems fine, thank you.
