### ISSUE TITLE
"Something went wrong" after stopping multiple short queries

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/Just-Data#99]
When I run code as below and press stop  just as first results start to appear, I'm getting "something went wrong" pop-up, then results keep appearing. Occasionally (2 in 5 times i tried) it stops earlier, then Justdata freezes when I'm trying to close tab.

select 1;select 1;select 1;select 1;select 1;select 1;select 1;select 1;select 1;select 1;select 1;select 1;select 1;

**Comment by KrzysztofDusko** [comment]
see if you can reproduce this error in version > 20211121.
But do not close this issue. More testing is needed.

**Comment by andrzejchmiel3** [comment]
Now it's better, it does not freeze.
However, sometimes I'm getting blank row in log like below, instead of "Aborted, connection closed". Tested on same code as in opening post.
![obraz](https://user-images.githubusercontent.com/93384978/142820554-f664a2c1-c4db-4c8c-930f-b46d53854e16.png)

**Comment by KrzysztofDusko** [comment]
i cannot reproduce on test environment,
Check again (should be "empty error message")

**Comment by andrzejchmiel3** [comment]
Nothing changed. when pressing stop, I'm getting one of  two outcomes:
- Normal log "Aborted, connection closed". This, I assume, is what you expected. (6 out of 10 tests)
- Red row in log with empty error message as in screenshot before. (4 out of 10 tests)

**Comment by KrzysztofDusko** [comment]
onlu empty message is problem, aborting works fine ?

**Comment by andrzejchmiel3** [comment]
Yes and yes

**Comment by KrzysztofDusko** [comment]
please check again ;)

**Comment by andrzejchmiel3** [comment]
Now it's better :) Either way I'm getting feedback what happened, so it should be sufficient. 
Closing thread, thank you
